export const projects = [
  {
    title: 'Comming soon',
    description: "",
    image: '/images/coming-soon.png',
    tags: ['', '', '', ''],
    source: '',
    visit: '',
    id: 0,
  },
  {
    title: 'Comming soon',
    description: "",
    image: '/images/coming-soon.png',
    tags: ['', '', '', ''],
    source: '',
    visit: '',
    id: 1,
  },
  // {
  //   title: 'Comming soon',
  //   description: "",
  //   image: '/images/coming-soon.png',
  //   tags: ['', '', '', ''],
  //   source: '',
  //   visit: '',
  //   id: 2,
  // },
  // {
  //   title: 'Comming soon',
  //   description: "",
  //   image: '/images/coming-soon.png',
  //   tags: ['', '', '', ''],
  //   source: '',
  //   visit: '',
  //   id: 3,
  // },
  // {
  //   title: 'Comming soon',
  //   description: "",
  //   image: '/images/coming-soon.png',
  //   tags: ['', '', '', ''],
  //   source: '',
  //   visit: '',
  //   id: 4,
  // },
  // {
  //   title: 'Comming soon',
  //   description: "",
  //   image: '/images/coming-soon.png',
  //   tags: ['', '', '', ''],
  //   source: '',
  //   visit: '',
  //   id: 5,
  // },

];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a new developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Got a scholarship from the Delhi government.', },
  { year: 2021, text: 'Still trying to figure out this weird year.', },
];